### ISSUE TITLE
Slow training speed

### ISSUE THREAD

**Issue by SkyAndCloud** [DAMO-NLP-SG/CLEX#3]
Hi, I found that the forward and backward passes of `odeint` is very slow. It is probably caused by too much iterations during  solving the Neural ODE. The backward process is similar to RNN's BPTT. Have you test the training latency in your experiments? How is it compared to the baselines settings, such as PI and Yarn.

**Comment by guanzhchen** [comment]
Hi, thanks for your interest! Can you provide your experimental settings (training length, base model, GPUs)? Have you compared the training speed w/ and w/o CLEX on your setting?

I trained CLEX-7B on 8xA100 80G, where I didn't find there would be significant extra latency (usually 1%~2%). The backward process indeed like BPTT, but the networks are just two 64x128 FFN which are very small. Even if they need to be forward and backward multiple times, I don't think it would be a bottleneck.
