### ISSUE TITLE
Unable to load model 

### ISSUE THREAD

**Issue by kmussa1993** [DAMO-NLP-SG/CLEX#4]
Hi,

I am getting following error when trying to load the model using AutoModelFromCausalLM 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1099, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 774, in from_dict
    config = cls(**config_dict)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 160, in __init__
    self._rope_scaling_validation()
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 180, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with with two fields, `type` and `factor`, got {'max_factor': 16, 'param_factor': 1, 'type': 'clex', 'factor': 1}

and when trying to load it via PhiForCausalLM, I got error during generate 
  File "/opt/conda/envs/clex/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/clex/lib/python3.10/site-packages/flash_attn/bert_padding.py", line 17, in forward
    return torch.gather(
RuntimeError: index 17 is out of bounds for dimension 0 with size 7

Can you please guide me on how to set this up properly?

**Comment by guanzhchen** [comment]
Hi, thanks for your interest!

1. Please specify `trust_remote_code=True` in `from_pretrained` as we have a custom config and model class, otherwise it would load default LLaMA classes and result in the errors.
2. We specify using flash attention for all models, so I guess this is because you don't use flash attention in `from_pretrained` by `use_flash_attention_2=True`. Sorry for the inconvenience and now I have fixed it so you can choose to use flash attention or not.

**Comment by kmussa1993** [comment]
Hi @guanzhchen, 
Thank you so much for fixing this quickly. I will give this a try in a bit. Another quick question, for finetuning specifically SFT I still need to use clex layer as well, right? I saw you guys have SFT script. Did you guys already tried SFT? Does it work well in your case?

**Comment by guanzhchen** [comment]
We have done SFT on CLEX-Mixtral and CLEX-LLaMA and it indeed shows some promising extrapolation ability, as shown in the results on [InfiniteBench](https://github.com/DAMO-NLP-SG/CLEX?tab=readme-ov-file#infinitebench) and [LongBench](https://github.com/DAMO-NLP-SG/CLEX#longbench).

When doing SFT, I still recommend using the clex layer and tuning it if you want to achieve extrapolation instruction-following ability. I have verified that fixing the clex layer during SFT would produce poorer instruction-following ability when testing beyond SFT length.

**Comment by kmussa1993** [comment]
@guanzhchen  Thank you so much! This is all really helpful. Just last question, when finetuning or continuing to pretrain what is the max_model_length that should be used? So for example if I am already using DAMO-NLP-SG/CLEX-Phi-2-32K, the max_model_length should be 32k or should be what I want my sequences to be? For both the train scripts I see 4k, I assume this is just to return the constant length dataset so, it should be 99th percentile of your training data. Is my understanding correct?

**Comment by guanzhchen** [comment]
@kmussa1993 The max_model_length should be within the range of `max_factor*max_position_embedding` (both args are shown in the config). The `max_factor` is bounded with the native context length (i.e., 2k for Phi-2) rather than the training length, so you can choose any training sequence within this threshold.
BTW, the choice may affect the extrapolation ability, for example, if you want to extrapolate to 128k, training on 32k is probably better than training on 16k. However, I guess the gap would not be very large if SFT upon our base model (e.g., DAMO-NLP-SG/CLEX-Phi-2-32K).

**Comment by kmussa1993** [comment]
Hi @guanzhchen, 

Thank you so much. I will give it a try. My plan is to continue Pretraining for a bit, and see if sft helps. 
Thanks again for the help and much appreciated

**Comment by kmussa1993** [comment]
Hi again, 

Just fyi, the zero3 config for deepspeed are missing in playground.

**Comment by guanzhchen** [comment]
Sorry for the omission. Now I have added the zero_2, zero_3 and zero_3_offload configs. You are not necessary to use zero_3_offload, please choose the config according to your GPU resource.

**Comment by kmussa1993** [comment]
Yes, I have skipped these for now. One more thing during training it creates clex_args via this build_clex_args function. The time_dt field is missing there. Whereas in the config it is required.

**Comment by guanzhchen** [comment]
time_dt is always set as 0.01. please add it to the arguments (like what the newest commit done) or just set it as a fixed value in clex_layer.py.

**Comment by guanzhchen** [comment]
It's a refactoring version which is different from the dev version I use, I apologize for any omitted details and feel free to drop any questions here.

**Comment by kmussa1993** [comment]
Yes, I added that :) it worked. Also what about chars_per_token. I see there is a function to calculate this but never used and hard coded to a specific value. Should I change it to that function or keep it constant. For now, I changed it but it says tokens() is only available for fast tokenizers

**Comment by kmussa1993** [comment]
Oh I fixed it by setting use_fast=True, sorry for my dumb questions here and thank you so much for responding this quickly.

**Comment by kmussa1993** [comment]
Hi @guanzhchen, 

Did you have any problem when loading model using resume_from_checkpoint =True? when I am doing this it takes too long to start training making it seems like hanged. Not sure if its hanged or something else.
