### ISSUE TITLE
TypeError: field() got an unexpected keyword argument 'choices'

### ISSUE THREAD

**Issue by jychen01** [DAMO-NLP-SG/CLEX#5]
Hi, I found an error when I ran the training code: `TypeError: field() got an unexpected keyword argument 'choices'`. 
Can you tell me how to solve this problem? I think it may be caused by version of package `dataclasses`.

**Comment by guanzhchen** [comment]
Hi, this is a bug and the `choices` should be included in the metadata.  Thank you for pointing it our and we have fixed it. Feel free to let me know if you have more questions.
