### ISSUE TITLE
huggingface开源模型配置有问题？

### ISSUE THREAD

**Issue by xjwhy** [DAMO-NLP-SG/CLEX#6]
作者你好，在使用你的开源模型推理中发现了一个问题

https://huggingface.co/DAMO-NLP-SG/CLEX-7B-16K/blob/main/clex_layer.py 里面的CLEXScalingRotaryEmbedding推理是forward(self, input_embeds, seq_len, do_train=False)
但是modeling_llama里面的推理是
pack_cos_sin = self.clex_layer(inputs_embeds.device, inputs_embeds.dtype, seq_length + past_key_values_length, self.training)
这里的参数是不是对不上

**Comment by guanzhchen** [comment]
你好，这里是在兼容其他模型时没有统一旧接口，本质这里就是要传入device和dtype信息， 感谢指出我们的问题，我们会迅速修正！

**Comment by xjwhy** [comment]
ok

**Comment by guanzhchen** [comment]
fixed!

**Comment by wj882018** [comment]
你好，我在跑llama2-7b-chat时，也碰到这个问题，  请问最新代码还没有上传吗
File "/CLEX/CLEX/llama/modeling_llama_clex.py", line 1118, in forward
    pack_cos_sin = self.clex_layer(inputs_embeds.device, inputs_embeds.dtype, seq_length + past_key_values_length, self.training)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given

**Comment by guanzhchen** [comment]
你好，可以考虑使用我们huggingface上的实现https://huggingface.co/DAMO-NLP-SG/CLEX-7B-16K/blob/main/modeling_llama.py，我们测试是从hugging face上load来进行的，不好意思github上的可能随着代码refactoring更新不及时

**Comment by wj882018** [comment]
你好，我看了一下训练数据代码那块是content，也就是预训练数据。问一下微调数据（输入、输出）这种，是直接concat为一段，然后直接训练吗
